name: windows_ocr_example
description: Demonstrates how to use the windows_ocr plugin.
publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  file_picker: ^5.0.1
  windows_ocr:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
