name: windows_ocr
description: Windows OCR.
version: 0.0.1
homepage: https://github.com/hamdikahloun/windows_ocr

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsOcrPlugin
